baseURL: https://electaco.github.io/
languageCode: en-us
title: Electaco
#theme: ananke
theme: PaperMod
menu:
  main:
   - url: /howtos
     name: How-to's
params:
  assets:
   favicon: favicon.svg
   faviconType: image/svg+xml